Modified my caption - #2
githubschool/jubilant-meme pull request #10
Opened 2022-01-18 20:06 UTC by cdcrchrisparker

Added new info to my slide:
- [x] Introduction to my name
- [ ] Info about me

Associated with issue #2

2022-01-18 20:18 UTC, IntellexLLC requested changes

2022-01-18 20:18 UTC, IntellexLLC commented on _slides/05-cdcrchrisparker.md
> +Hello, my name is **Chris**.
Pleasure to meet you **Chris**.  It's nice to meet you. Can you also give us a cool fact about yourself?

2022-01-18 20:18 UTC, IntellexLLC commented on _slides/05-cdcrchrisparker.md
>  title: "Welcome to our slide deck!"
`New code needed`

2022-01-18 20:20 UTC, cdcrchrisparker commented on _slides/05-cdcrchrisparker.md
> +Hello, my name is **Chris**.
I'd love to give a cool fact, can't think of anything under the pressure of the moment.

2022-01-19 18:39 UTC, IntellexLLC approved these changes
Nicely down 🚀

2022-01-19 18:48 UTC, cdcrchrisparker commented
Rebase and merge here

2022-01-19 18:49 UTC, cdcrchrisparker commented
Rebase and merge

2022-01-19 18:50 UTC, cdcrchrisparker commented
Rebase and merge

2022-01-19 19:03 UTC, merged