Updating Slide
githubschool/jubilant-meme pull request #12
Opened 2022-01-18 20:06 UTC by satishone

Adding new items to my slide:
- [x] Introduction to myself
- [ ] Cool about myself

Associated with issue #2

2022-01-18 20:18 UTC, cdcrabhavsar requested changes

2022-01-18 20:18 UTC, cdcrabhavsar commented on _slides/10-satishone.md
It's nice to meet you. Can you give us a cool fact about yourself?

2022-01-18 21:22 UTC, satishone commented on _slides/10-satishone.md
I like to play and watch cricket.

2022-01-19 18:40 UTC, cdcrabhavsar requested changes
You added the cool fact in the comment and not in the code. update code file and send for review. Thanks

2022-01-19 18:54 UTC, selkins13 approved these changes

2022-01-19 18:55 UTC, merged