adding my introduction to my slide - #2
githubschool/jubilant-meme pull request #9
Opened 2022-01-18 20:06 UTC by DieselClark

Extra Notes! Adding  new items to my slide
- [x] Introduction to myself
- [ ] Cool about myself

Associated with issue#2

2022-01-18 20:18 UTC, cdcrchrisparker requested changes

2022-01-18 20:18 UTC, cdcrchrisparker commented on _slides/03-DieselClark.md
> +Hello, my name is Kyle Clark.
Please also add a cool fact about yourself.

2022-01-18 21:30 UTC, DieselClark commented on _slides/03-DieselClark.md
> +Hello, my name is Kyle Clark.
I like to BBQ!

2022-01-19 18:39 UTC, cdcrchrisparker approved these changes
:rocket: Ready to go!

2022-01-19 18:49 UTC, merged